# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Major).$(Minor)$(rev:.r).$(BuildID)

trigger:
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 
    enableCodeCoverage: false

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'stage'
    enableCodeCoverage: false

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'prod'
    enableCodeCoverage: false

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'cdn'
    arguments: '--ver $(Build.BuildNumber)'
    enableCodeCoverage: false

- task: ArchiveFiles@2
  displayName: 'Archive Dev files'
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'

- task: ArchiveFiles@2
  displayName: 'Archive cdn files'
  inputs:
    rootFolderOrFile: cdn
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/cdn.zip'

- task: ArchiveFiles@2
  displayName: 'Archive prod files'
  inputs:
    rootFolderOrFile: prod
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/prod.zip'


- task: ArchiveFiles@2
  displayName: 'Archive staging files'
  inputs:
    rootFolderOrFile: staging
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/staging.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'


